### ISSUE TITLE
Differences in Web Interface vs R Wrapper, general usage questions

### ISSUE THREAD

**Issue by fratajcz** [PavlidisLab/gemma.R#16]
Hi!

I have just started working with gemma and I will need to access the database programmatically and frequently to assess the results of an automated pipeline. I will produce gene sets and will need to know if these genes are statistically significant in differential expression in a given disease. I first had a look at the web interface and managed to get what I needed. Then I wanted to use the ```gemma.R``` library and found no way of achieving the same result. My questions in detail are as follows:

1. Using the same search query, the returned datasets differ slightly:
  - If I type "immune dysregulation" in the web interface, it says "55 out of 58 have diff. expression data available" and returns ( or shows) only the 55 where the data is available. Whereas if I use ```searchDatasets('immune dysregulation', limit = 100, taxon = 'human')```it returns the full 58 and I do not know by which flag I can filter if they contain expression data or not.

2. Checking for batch effects
From what I've seen it is possible to check whether the experiments have been batch corrected (ee.batchCorrected), but I can't find a value that tells me if batch correction was even necessary. I.e. if the experiment was single-batch or there was no batch effect found.

3. Telling the experiment labelDescription without downloading expression data
I tried to find out which of the returned experiments are disease vs control, but the only data structure where I found this information was when I download the expression data (i.e. using ```eset <- getBioc('ExpressionSet', 'GSE28548')```) and then check the field ```eset@phenoData@varMetadata$labelDescription```. However, it seems very wasteful to download all the data just to check this and then throw it away again if it is not the desired type. Is there a more clever way to do that?

4. Getting p-values
This might sound naive, but even if I get a list of appropriate experiments, is there a function that allows me to chuck in a list of genes and the list of experiments and just returns the logfold change in expression and the pvals, just as with the Web Interface? 

5. Curated lists of experiments
I have noticed that there are pre-configured curated lists of experiments available in the web interface, i.e. "Alzheimer's Disease" or "Human Inflammatory Bowel Disease". Is there a full list somewhere of those pre-configured lists? I am afraid the a simple search query might return erroneous experiments in some cases which might mess up my results. 

Thanks a lot in advance, I know that maintaining a public resource can be a pain in the *** sometimes and I hope I don't cause too much  of a hassle.

**Comment by yavyx** [comment]
First of all thanks for your feedback! This wrapper is under active development and user feedback is very valuable to us at this stage.

1. There isn’t a specific flag that indicates if there is differential expression data for a given dataset. I reimplemented a `getDatasetDEA()` endpoint which returns information about the differential expression analysis for the queried dataset. You can loop over your datasets and call this endpoint, if it returns an empty list it means there is no differential expression data for that dataset.

2. I exposed an `ee.batchEffect` flag that was hidden before, it should have the information you need.
    
3. You can use  `getDatasetResultsets()` which gives you a short summary of the factors and the levels used in the differential expression analysis for that dataset. Keep in mind that a dataset may have more than one differential expression analysis (resultSet) associated with it.

4. There isn’t a specific function to do this as of now, you would need to use `getDatasetDE()` to get the desired differential expression tables, then filter them using your genes of interest. In this initial release of the R wrapper we are focusing on just accessing the expression and differential expression data, but we might implement this functionality in a future release.

5. These lists are actually outdated and we eventually plan to phase them out, since it is difficult to assign with certainty which datasets belong in a particular list. We recommend that you use the search feature and decide for yourself if the retrieved datasets are of interest.

If you have any other questions or need more assistance, I’m happy to help!
